### ISSUE TITLE
Cannot find module 'webpack/lib/removeAndDo'

### ISSUE THREAD

**Issue by summerinsect** [nowa-webpack/nowa#18]
nowa build

module.js:327
    throw err;
    ^

Error: Cannot find module 'webpack/lib/removeAndDo'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/admin/.nowa/install/extract-text-webpack-plugin/1.0.1/extract-text-webpack-plugin/ExtractedModule.js:30:42)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

**Comment by gbk** [comment]
Something go wrong when you install nowa. So please reinstall nowa.

```
sudo npm uninstall nowa -g
sudo npm i nowa -g --registry=https://registry.npm.taobao.org
nowa install --registry=https://registry.npm.taobao.org
```

**Comment by gbk** [comment]
重装 node 之后这个问题还会重现么？

**Comment by summerinsect** [comment]
ok了，一并解决

**Comment by gbk** [comment]
:+1: 大赞
