### ISSUE TITLE
无法安装啊

### ISSUE THREAD

**Issue by singleclown** [nowa-webpack/nowa#28]
第三方第三方的

**Comment by gbk** [comment]
报什么错？

**Comment by singleclown** [comment]
module.js:471
    throw err;
    ^

Error: Cannot find module 'inquirer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sigmundliu/.nowa/install/nowa-init/1.3.0/nowa-init/src/proj.js:13:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by gbk** [comment]
@singleclown 

sudo npm uninstall nowa -g
sudo npm cache clean
sudo rm -rf ~/.nowa ~/.npminstall_tarball
sudo npm i nowa -g --registry=https://registry.npm.taobao.org
sudo chmod 777 \`npm root -g\`
nowa install --registry=https://registry.npm.taobao.org

**Comment by singleclown** [comment]
我nowa1.1.0应该就是nowa已经安装好了，然后初始化项目有问题是吧

**Comment by singleclown** [comment]
Download 'alias.json' from 'https://raw.githubusercontent.com/nowa-webpack/template-alias/master/alias.json'.一直卡着20分钟了

**Comment by gbk** [comment]
你的网络好像有问题啊。。。github 的资源访问不了么？
直接在浏览器里面打开行么？
https://raw.githubusercontent.com/nowa-webpack/template-alias/master/alias.json

**Comment by singleclown** [comment]
已经好了，谢了，但是我不太会用这个，再研究研究

**Comment by singleclown** [comment]
不用这个开发工具是不是也可以得

**Comment by singleclown** [comment]
Debugger listening on [::]:34260
module.js:471
    throw err;
    ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/sigmundliu/Downloads/openapi-demo-nodejs-master/app.js:1:77)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)这个是运行demo node.js报的错，是不是也是同样解决方法

**Comment by gbk** [comment]
是的，怀疑你的网络不太稳定

**Comment by singleclown** [comment]
那个已经好了，我是运行node.js的demo(sdk)又出现这个问题，是网络不稳定？应该不是吧，

**Comment by gbk** [comment]
Cannot find module 的问题还是 Download 的问题？

**Comment by singleclown** [comment]
找不到模块

**Comment by singleclown** [comment]
找不到模块，我还是用同样地方法解决嘛？

**Comment by singleclown** [comment]
找不到模块，我还是用同样地方法解决嘛？但是是另外一个服务端的demo运行出现这问题，nodejs写得

**Comment by singleclown** [comment]
找不到模块，我还是用同样地方法解决嘛？但是是另外一个服务端的demo运行出现这问题，nodejs写得

**Comment by singleclown** [comment]
找不到模块，我还是用同样地方法解决嘛？但是是另外一个服务端的demo运行出现这问题，nodejs写得

**Comment by singleclown** [comment]
找不到模块，我还是用同样地方法解决嘛？但是是另外一个服务端的demo运行出现这问题，nodejs写得

**Comment by singleclown** [comment]
找不到模块，我还是用同样地方法解决嘛？但是是另外一个服务端的demo运行出现这问题，nodejs写得

**Comment by singleclown** [comment]
找不到模块，我还是用同样地方法解决嘛？但是是另外一个服务端的demo运行出现这问题，nodejs写得

**Comment by singleclown** [comment]
找不到模块，我还是用同样地方法解决嘛？但是是另外一个服务端的demo运行出现这问题，nodejs写得

**Comment by gbk** [comment]
另外一个服务端的 demo？
是用 nowa 起的服务吗？

**Comment by singleclown** [comment]
没有用，只是运行了而已，出现同样错误，我就索性来问问呢

**Comment by gbk** [comment]
那不是同一个问题。
估计你得运行一下 npm install

**Comment by singleclown** [comment]
犀利
