### ISSUE TITLE
Nowa Build在Ubuntu 16.04桌面环境下出错

### ISSUE THREAD

**Issue by LiangZugeng** [nowa-webpack/nowa#29]
按照安装步骤安装了Nowa，node版本6.9.2，npm版本3.10.9，但是在运行nowa build的时候提示：

Error: Cannot find module 'webpack/lib/removeAndDo'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/james/.nowa/install/extract-text-webpack-plugin/1.0.1/extract-text-webpack-plugin/ExtractedModule.js:30:42)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

我是使用的n来办理node版本，目前使用的node版本是n lts自动装的。

麻烦帮忙看一下，给点思路。

**Comment by gbk** [comment]
https://github.com/nowa-webpack/nowa/issues/17 很抱歉，npminstall 不是很文档，请参考这个 issue 尝试卸载重新安装

**Comment by LiangZugeng** [comment]
谢谢，可能是nowa的npm包文件的问题，就算从npm.taobao.org安装的nowa都会有错。

我昨晚自己解决了这个问题，基本上就是把nowa重新装一遍，不过使用了自己的代理服务器和npm，源是国外的源。在nowa install后nowa init uxcore，创建一个模版项目，先保证模版项目可以build，salt-ui的demo就没问题了。

这个问题可能是由于nowa install的时候下载的包中webpack文件损坏或者不全导致的，需要用稳定的国外网络连接全部重新装。你给的issue里的解决方案基本上就能解决了。此问题我会关闭。谢谢。

另外，貌似你们阿里的人在阿里钉钉论坛上回复得很少，我这个问题在那边发了一周了，没人理，你这边回复很快，这点要重点称赞一下！！

**Comment by gbk** [comment]
很抱歉，github 是有邮件订阅的，论坛帖子比较难找，你把链接发我一下？

**Comment by LiangZugeng** [comment]
Sorry，没有及时回复。钉钉开发者支持论坛的问题地址：https://bbs.aliyun.com/read/302544.html?spm=5176.bbsl369.0.0.enSEeM。
