### ISSUE TITLE
nowa init报错

### ISSUE THREAD

**Issue by paseo** [nowa-webpack/nowa#3]
执行下列命令报错：
```
tnpm i -g nowa

nowa install

nowa init
```

报错信息：
```
module.js:327
    throw err;
    ^

Error: Cannot find module 'inquirer'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/.npminstall/nowa-init/0.1.16/nowa-init/src/proj.js:13:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)

```

软件信息：
```
tnpm@2.12.2
npm@2.15.6
node@4.3.2
npminstall@1.10.1
darwin x64 15.15.0
```

直接使用npm安装也报错，npm版本3.9.5

**Comment by gbk** [comment]
https://github.com/nowa-webpack/nowa/issues/2
