### ISSUE TITLE
Cannot find module 'inquirer'

### ISSUE THREAD

**Issue by lgyytm** [nowa-webpack/nowa#43]
I've installed inquirer,but it still warns this
`nowa init uxcore
module.js:471
    throw err;
    ^

Error: Cannot find module 'inquirer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (.nowa\install\.1.6.0@nowa-init\src\proj.js:13:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)`

**Comment by gbk** [comment]
请参考常见问题1 解决。
https://nowa-webpack.github.io/docs/chang_jian_wen_ti.html

**Comment by lgyytm** [comment]
mac可能可以解决，但是win那个方法不行，还有一个问题，众所周知的原因是系统问题吗？

**Comment by gbk** [comment]
win 下用 linux 模拟器，或者打开文件夹删除对应的目录
众所周知的原因是墙啊

**Comment by lgyytm** [comment]
好的，谢谢哈
