### ISSUE TITLE
nowa init uxcore的时候出现了问题 gbk麻烦看下

### ISSUE THREAD

**Issue by kvkens** [nowa-webpack/nowa#46]
hello,我在使用nowa初始化的时候出现了模块找不到的问题，我看了下nowa是在.nowa文件夹内放了一些中间件，所以我就不太明白nowa的工作原理，错误如下：

```bash
bogon:install kvkens$ nowa init uxcore
module.js:471
    throw err;
    ^

Error: Cannot find module 'inquirer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/kvkens/.nowa/install/_nowa-init@1.8.0@nowa-init/src/proj.js:13:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

希望gbk看下是我的某一项出了问题还是? :)

**Comment by gbk** [comment]
https://nowa-webpack.github.io/docs/chang_jian_wen_ti.html
很抱歉，请按常见问题处理一下吧

**Comment by kvkens** [comment]
@gbk 好的，我觉得这应该发到nowa-init里哈。

3Q
