### ISSUE TITLE
nowa 1.2.1 uninstall Windows 错误

### ISSUE THREAD

**Issue by ywzhaiqi** [nowa-webpack/nowa#54]
运行命令 `npm uninstall -g nowa`，结果错误

    > nowa@1.2.1 preuninstall C:\Users\XXX\AppData\Roaming\npm\node_modules\nowa
    > node ./uninstall.js

    C:\Users\XXX\.nowa\install\.bin\rimraf:2
    basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
              ^^^^^^^

    SyntaxError: missing ) after argument list
        at createScript (vm.js:74:10)
        at Object.runInThisContext (vm.js:116:10)
        at Module._compile (module.js:537:28)
        at Object.Module._extensions..js (module.js:584:10)
        at Module.load (module.js:507:32)
        at tryModuleLoad (module.js:470:12)
        at Function.Module._load (module.js:462:3)
        at Function.Module.runMain (module.js:609:10)
        at startup (bootstrap_node.js:158:16)
        at bootstrap_node.js:598:3
    child_process.js:634
        throw err;
        ^

    Error: Command failed: node C:\Users\XXX\.nowa\install\.bin\rimraf ../nowa-* C:\Users\XXX\.nowa\install\*
    C:\Users\XXX\.nowa\install\.bin\rimraf:2
    basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
              ^^^^^^^

    SyntaxError: missing ) after argument list

只好手动删除 `C:\Users\XXX\.nowa` 目录

**Comment by gbk** [comment]
是用 cmd 执行的么？
可否用 bash 来跑？
