### ISSUE TITLE
nowa编译报错

### ISSUE THREAD

**Issue by wangxc1314** [nowa-webpack/nowa#66]
C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@7.16.0@npm\lib\cli.js:40
npm.load(async er => { 
^^^^^ 
SyntaxError: missing ) after argument list 
at Object.exports.runInThisContext (vm.js:76:16) 
at Module._compile (module.js:542:28) 
at Object.Module._extensions..js (module.js:579:10) 
at Module.load (module.js:487:32) 
at tryModuleLoad (module.js:446:12) 
at Function.Module._load (module.js:438:3) 
at Module.require (module.js:497:17) 
at require (internal/module.js:20:19) 
at Object. (C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@7.16.0@npm\bin\npm-cli.js:2:1) 
at Module._compile (module.js:570:32)

**Comment by gbk** [comment]
抱歉，这个工具目前已经停止维护。
从报错来看，似乎是 npm 7.16.0 使用了 es6 语法，而当前环境不支持。
