### ISSUE TITLE
哇 启动成这个样子了 搞了一两天都没好 同事的都可以就我的出问题 麻烦帮看看吧

### ISSUE THREAD

**Issue by wangxc1314** [nowa-webpack/nowa#67]
info error reading version SyntaxError: Unexpected token in JSON at position 0 while parsing near '...'
info error reading version at Object.parse (native)
info error reading version at parseJson (C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\node_modules\json-parse-better-errors\index.js:7:17)
info error reading version at module.exports (C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\lib\utils\parse-json.js:4:10)
info error reading version at C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\lib\npm.js:81:13
info error reading version at Object. (C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\lib\npm.js:476:3)
info error reading version at Module._compile (module.js:570:32)
info error reading version at Object.Module._extensions..js (module.js:579:10)
info error reading version at Module.load (module.js:487:32)
info error reading version at tryModuleLoad (module.js:446:12)
info error reading version at Function.Module._load (module.js:438:3)
info error reading version at Module.require (module.js:497:17)
info error reading version at require (internal/module.js:20:19)
info error reading version at Object. (C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\lib\config\figgy-config.js:8:13)
info error reading version at Module._compile (module.js:570:32)
info error reading version at Object.Module._extensions..js (module.js:579:10)
info error reading version at Module.load (module.js:487:32)
info error reading version { SyntaxError: Unexpected token in JSON at position 0 while parsing near '...'
info error reading version at Object.parse (native)
info error reading version at parseJson (C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\node_modules\json-parse-better-errors\index.js:7:17)
info error reading version at module.exports (C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\lib\utils\parse-json.js:4:10)
info error reading version at C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\lib\npm.js:81:13
info error reading version at Object. (C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\lib\npm.js:476:3)
info error reading version at Module._compile (module.js:570:32)
info error reading version at Object.Module._extensions..js (module.js:579:10)
info error reading version at Module.load (module.js:487:32)
info error reading version at tryModuleLoad (module.js:446:12)
info error reading version at Function.Module._load (module.js:438:3)
info error reading version at Module.require (module.js:497:17)
info error reading version at require (internal/module.js:20:19)
info error reading version at Object. (C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\lib\config\figgy-config.js:8:13)
info error reading version at Module._compile (module.js:570:32)
info error reading version at Object.Module._extensions..js (module.js:579:10)
info error reading version at Module.load (module.js:487:32)
info error reading version stack: 'SyntaxError: Unexpected token \u0000 in JSON at position 0 while parsing near \'\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000...\'\n at Object.parse (native)\n at parseJson (C:\\Users\\lenovo\\.nowa-gui\\installation\\node_modules\\.npminstall\\_npm@6.9.0@npm\\node_modules\\json-parse-better-errors\\index.js:7:17)\n at module.exports (C:\\Users\\lenovo\\.nowa-gui\\installation\\node_modules\\.npminstall\\_npm@6.9.0@npm\\lib\\utils\\parse-json.js:4:10)\n at C:\\Users\\lenovo\\.nowa-gui\\installation\\node_modules\\.npminstall\\_npm@6.9.0@npm\\lib\\npm.js:81:13\n at Object. (C:\\Users\\lenovo\\.nowa-gui\\installation\\node_modules\\.npminstall\\_npm@6.9.0@npm\\lib\\npm.js:476:3)\n at Module._compile (module.js:570:32)\n at Object.Module._extensions..js (module.js:579:10)\n at Module.load (module.js:487:32)\n at tryModuleLoad (module.js:446:12)\n at Function.Module._load (module.js:438:3)\n at Module.require (module.js:497:17)\n at require (internal/module.js:20:19)\n at Object. (C:\\Users\\lenovo\\.nowa-gui\\installation\\node_modules\\.npminstall\\_npm@6.9.0@npm\\lib\\config\\figgy-config.js:8:13)\n at Module._compile (module.js:570:32)\n at Object.Module._extensions..js (module.js:579:10)\n at Module.load (module.js:487:32)' }
C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\lib\npm.js:59
throw new Error('npm.load() required') 
^ 

Error: npm.load() required 
at Object.get (C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\lib\npm.js:59:13)
at mkConfig (C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\lib\config\figgy-config.js:29:35) 
at ci (C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\lib\ci.js:13:24)
at Object. (C:\Users\lenovo\.nowa-gui\installation\node_modules\.npminstall\_npm@6.9.0@npm\bin\npm-cli.js:2:24) 
at Module._compile (module.js:570:32) 
at Object.Module._extensions..js (module.js:579:10) 
at Module.load (module.js:487:32) 
at tryModuleLoad (module.js:446:12) 
at Function.Module._load (module.js:438:3) 
at Module.runMain (module.js:604:10) 
at run (bootstrap_node.js:394:7) 
at startup (bootstrap_node.js:149:9) 
at bootstrap_node.js:509:3

**Comment by gbk** [comment]
抱歉，这个工具目前已经停止维护。
从报错来看，似乎是 npm 6.9.0 使用了 es6 语法，而当前环境不支持。
